# This file is used to run integration tests on travis
version: '3'
services:

  janus_admin:
      image: daocloud.io/zhwei820/janus_admin
      ports:
        - "8082:80"
      environment:
        REACT_APP_JANUS_URI: http://localhost:8081
